name: Label issues
on:
  issues:
    types:
      - closed

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'triage'
            })
            
      - uses: actions/checkout@v3
        with:
          path: odc
          
      - name: Parse False Positive Issue
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          issue-body: ${{ github.event.issue.body }}
          template-path: odc/.github/ISSUE_TEMPLATE/false-positive-report.yml
